### ISSUE TITLE
yth_filter requires dimnames attribute

### ISSUE THREAD

**Issue by adzemski** [JustinMShea/neverhpfilter#1]
Generating an xts object from a vector using the xts::xts command does not (unless this is explicitly specified) endow the newly created object with a dimnames attribute. 

However running yth_filter on an xts object without a dimnames attribute will generate an error.

**Comment by JustinMShea** [comment]
Thanks for the heads up!

**Comment by JustinMShea** [comment]
This has been fixed, with branch `issue-1`, which has been merged to `master`. Look for release v0.3-0 to be posted soon, which will include updated data as well. See PR #2
